# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController

gripper_controller:
  ros__parameters:
    joints: 
      - gripper_finger1_joint
    type: joint_trajectory_controller/JointTrajectoryController
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
