ur_type: 'ur5e'
robot_ip: '192.168.56.101'
safety_limits: 'true'
safety_pos_margin: '0.15'
safety_k_position: '20'
demo_package: 'pick_and_place'
runtime_config_package: 'ur_config_utils'
controllers_file: 'ros2_controllers.yaml'
description_package: "ur_gripper_moveit_config"
description_file: 'ur_demo.urdf.xacro'
tf_prefix: '""'
use_fake_hardware: 'true'
fake_sensor_commands: 'false'
headless_mode: 'false'
controller_spawner_timeout: '10'
initial_joint_controller: 'joint_trajectory_controller'
activate_joint_controller: 'true'
launch_rviz: 'false'
launch_dashboard_client: 'true'
use_tool_communication: 'false'
tool_parity: '0'
tool_baud_rate: '115200'
tool_stop_bits: '1'
tool_rx_idle_chars: '1.5'
tool_tx_idle_chars: '3.5'
tool_device_name: '/tmp/ttyUR'
tool_tcp_port: '54321'
tool_voltage: '0'
reverse_ip: '0.0.0.0'
script_command_port: '50004'
